### ISSUE TITLE
Error on bash_hide_env[migrate gitlab-rails database]

### ISSUE THREAD

**Issue by dvorst** [gsdukbh/docker-gitlab-ee-arm64#1]
Is it possible to share instructions on how this image should be run?

I tried the command below, but it resulted in an error, I appended the error log at the end. It appears that no connection could be made with postgresql, could this be due to a wrongly configured port?.
```
docker run \
  --detach \
  --hostname gitlab.example.com \
  --publish 443:443 --publish 80:80 --publish 22:22 \
  --name gitlab \
  --restart always \
  --volume $GITLAB_HOME/config:/etc/gitlab \
  --volume $GITLAB_HOME/logs:/var/log/gitlab \
  --volume $GITLAB_HOME/data:/var/opt/gitlab \
  --shm-size 256m \
  gsdukbh/gitlab-ee-arm64
```

```
2023-10-10 10:07:17     * bash_hide_env[migrate gitlab-rails database] action run
2023-10-10 10:07:17       [execute] rake aborted!
2023-10-10 10:07:17                 ActiveRecord::DatabaseConnectionError: There is an issue connecting to your database with your username/password, username: gitlab.
2023-10-10 10:07:17                 
2023-10-10 10:07:17                 Please check your database configuration to ensure the username/password are valid.
2023-10-10 10:07:17                 /opt/gitlab/embedded/service/gitlab-rails/lib/gitlab/database/load_balancing/load_balancer.rb:116:in `read_write'
2023-10-10 10:07:17                 /opt/gitlab/embedded/service/gitlab-rails/lib/gitlab/database/load_balancing/connection_proxy.rb:126:in `write_using_load_balancer'
2023-10-10 10:07:17                 /opt/gitlab/embedded/service/gitlab-rails/lib/gitlab/database/load_balancing/connection_proxy.rb:96:in `method_missing'
2023-10-10 10:07:17                 /opt/gitlab/embedded/service/gitlab-rails/lib/tasks/gitlab/db.rake:115:in `configure_database'
2023-10-10 10:07:17                 /opt/gitlab/embedded/service/gitlab-rails/lib/tasks/gitlab/db.rake:101:in `block (3 levels) in <top (required)>'
2023-10-10 10:07:17                 /opt/gitlab/embedded/bin/bundle:25:in `load'
2023-10-10 10:07:17                 /opt/gitlab/embedded/bin/bundle:25:in `<main>'
2023-10-10 10:07:17                 
2023-10-10 10:07:17                 Caused by:
2023-10-10 10:07:17                 PG::ConnectionBad: connection to server on socket "/var/opt/gitlab/postgresql/.s.PGSQL.5432" failed: No such file or directory
2023-10-10 10:07:17                 Is the server running locally and accepting connections on that socket?
2023-10-10 10:07:17                 /opt/gitlab/embedded/service/gitlab-rails/lib/gitlab/database/load_balancing/load_balancer.rb:116:in `read_write'
2023-10-10 10:07:17                 /opt/gitlab/embedded/service/gitlab-rails/lib/gitlab/database/load_balancing/connection_proxy.rb:126:in `write_using_load_balancer'
2023-10-10 10:07:17                 /opt/gitlab/embedded/service/gitlab-rails/lib/gitlab/database/load_balancing/connection_proxy.rb:96:in `method_missing'
2023-10-10 10:07:17                 /opt/gitlab/embedded/service/gitlab-rails/lib/tasks/gitlab/db.rake:115:in `configure_database'
2023-10-10 10:07:17                 /opt/gitlab/embedded/service/gitlab-rails/lib/tasks/gitlab/db.rake:101:in `block (3 levels) in <top (required)>'
2023-10-10 10:07:17                 /opt/gitlab/embedded/bin/bundle:25:in `load'
2023-10-10 10:07:17                 /opt/gitlab/embedded/bin/bundle:25:in `<main>'
2023-10-10 10:07:17                 Tasks: TOP => gitlab:db:configure
2023-10-10 10:07:17                 (See full trace by running task with --trace)
2023-10-10 10:07:17       
2023-10-10 10:07:17       ================================================================================
2023-10-10 10:07:17       Error executing action `run` on resource 'bash_hide_env[migrate gitlab-rails database]'
2023-10-10 10:07:17       ================================================================================
2023-10-10 10:07:17       
2023-10-10 10:07:17       Mixlib::ShellOut::ShellCommandFailed
2023-10-10 10:07:17       ------------------------------------
2023-10-10 10:07:17       Expected process to exit with [0], but received '1'
2023-10-10 10:07:17       ---- Begin output of "bash"  ----
2023-10-10 10:07:17       STDOUT: rake aborted!
2023-10-10 10:07:17       ActiveRecord::DatabaseConnectionError: There is an issue connecting to your database with your username/password, username: gitlab.
2023-10-10 10:07:17       
2023-10-10 10:07:17       Please check your database configuration to ensure the username/password are valid.
2023-10-10 10:07:17       /opt/gitlab/embedded/service/gitlab-rails/lib/gitlab/database/load_balancing/load_balancer.rb:116:in `read_write'
2023-10-10 10:07:17       /opt/gitlab/embedded/service/gitlab-rails/lib/gitlab/database/load_balancing/connection_proxy.rb:126:in `write_using_load_balancer'
2023-10-10 10:07:17       /opt/gitlab/embedded/service/gitlab-rails/lib/gitlab/database/load_balancing/connection_proxy.rb:96:in `method_missing'
2023-10-10 10:07:17       /opt/gitlab/embedded/service/gitlab-rails/lib/tasks/gitlab/db.rake:115:in `configure_database'
2023-10-10 10:07:17       /opt/gitlab/embedded/service/gitlab-rails/lib/tasks/gitlab/db.rake:101:in `block (3 levels) in <top (required)>'
2023-10-10 10:07:17       /opt/gitlab/embedded/bin/bundle:25:in `load'
2023-10-10 10:07:17       /opt/gitlab/embedded/bin/bundle:25:in `<main>'
2023-10-10 10:07:17       
2023-10-10 10:07:17       Caused by:
2023-10-10 10:07:17       PG::ConnectionBad: connection to server on socket "/var/opt/gitlab/postgresql/.s.PGSQL.5432" failed: No such file or directory
2023-10-10 10:07:17       Is the server running locally and accepting connections on that socket?
2023-10-10 10:07:17       /opt/gitlab/embedded/service/gitlab-rails/lib/gitlab/database/load_balancing/load_balancer.rb:116:in `read_write'
2023-10-10 10:07:17       /opt/gitlab/embedded/service/gitlab-rails/lib/gitlab/database/load_balancing/connection_proxy.rb:126:in `write_using_load_balancer'
2023-10-10 10:07:17       /opt/gitlab/embedded/service/gitlab-rails/lib/gitlab/database/load_balancing/connection_proxy.rb:96:in `method_missing'
2023-10-10 10:07:17       /opt/gitlab/embedded/service/gitlab-rails/lib/tasks/gitlab/db.rake:115:in `configure_database'
2023-10-10 10:07:17       /opt/gitlab/embedded/service/gitlab-rails/lib/tasks/gitlab/db.rake:101:in `block (3 levels) in <top (required)>'
2023-10-10 10:07:17       /opt/gitlab/embedded/bin/bundle:25:in `load'
2023-10-10 10:07:17       /opt/gitlab/embedded/bin/bundle:25:in `<main>'
2023-10-10 10:07:17       Tasks: TOP => gitlab:db:configure
2023-10-10 10:07:17       (See full trace by running task with --trace)
2023-10-10 10:07:17       STDERR: 
2023-10-10 10:07:17       ---- End output of "bash"  ----
2023-10-10 10:07:17       Ran "bash"  returned 1
2023-10-10 10:07:17       
2023-10-10 10:07:17       Cookbook Trace: (most recent call first)
2023-10-10 10:07:17       ----------------------------------------
2023-10-10 10:07:17       /opt/gitlab/embedded/cookbooks/cache/cookbooks/gitlab/resources/rails_migration.rb:20:in `block in class_from_file'
2023-10-10 10:07:17       
2023-10-10 10:07:17       Resource Declaration:
2023-10-10 10:07:17       ---------------------
2023-10-10 10:07:17       # In /opt/gitlab/embedded/cookbooks/cache/cookbooks/gitlab/resources/rails_migration.rb
2023-10-10 10:07:17       
2023-10-10 10:07:17        20:   bash_hide_env "migrate #{new_resource.name} database" do
2023-10-10 10:07:17        21:     code <<-EOH
2023-10-10 10:07:17        22:     set -e
2023-10-10 10:07:17        23:     log_file="#{logging_settings[:log_directory]}/#{new_resource.logfile_prefix}-$(date +%Y-%m-%d-%H-%M-%S).log"
2023-10-10 10:07:17        24:     umask 077
2023-10-10 10:07:17        25:     /opt/gitlab/bin/gitlab-rake #{new_resource.rake_task} 2>& 1 | tee ${log_file}
2023-10-10 10:07:17        26:     STATUS=${PIPESTATUS[0]}
2023-10-10 10:07:17        27:     chown #{account_helper.gitlab_user}:#{account_helper.gitlab_group} ${log_file}
2023-10-10 10:07:17        28:     echo $STATUS > #{new_resource.helper.db_migrate_status_file}
2023-10-10 10:07:17        29:     exit $STATUS
2023-10-10 10:07:17        30:     EOH
2023-10-10 10:07:17        31: 
2023-10-10 10:07:17        32:     environment new_resource.environment if new_resource.property_is_set?(:environment)
2023-10-10 10:07:17        33:     new_resource.dependent_services.each do |svc|
2023-10-10 10:07:17        34:       notifies :restart, svc, :immediately
2023-10-10 10:07:17        35:     end
2023-10-10 10:07:17        36: 
2023-10-10 10:07:17        37:     not_if { new_resource.helper.migrated? }
2023-10-10 10:07:17        38:     sensitive false
2023-10-10 10:07:17        39:   end
2023-10-10 10:07:17        40: end
2023-10-10 10:07:17       
2023-10-10 10:07:17       Compiled Resource:
2023-10-10 10:07:17       ------------------
2023-10-10 10:07:17       # Declared in /opt/gitlab/embedded/cookbooks/cache/cookbooks/gitlab/resources/rails_migration.rb:20:in `block in class_from_file'
2023-10-10 10:07:17       
2023-10-10 10:07:17       bash_hide_env("migrate gitlab-rails database") do
2023-10-10 10:07:17         action [:run]
2023-10-10 10:07:17         default_guard_interpreter :default
2023-10-10 10:07:17         interpreter "bash"
2023-10-10 10:07:17         declared_type :bash_hide_env
2023-10-10 10:07:17         cookbook_name "gitlab"
2023-10-10 10:07:17         recipe_name "database_migrations"
2023-10-10 10:07:17         code "    set -e\n    log_file=\"/var/log/gitlab/gitlab-rails/gitlab-rails-db-migrate-$(date +%Y-%m-%d-%H-%M-%S).log\"\n    umask 077\n    /opt/gitlab/bin/gitlab-rake gitlab:db:configure 2>& 1 | tee ${log_file}\n    STATUS=${PIPESTATUS[0]}\n    chown git:git ${log_file}\n    echo $STATUS > /var/opt/gitlab/gitlab-rails/upgrade-status/db-migrate-873248b1f0d3a7a5535771a3a1635803-fedb711c3d2\n    exit $STATUS\n"
2023-10-10 10:07:17         environment "*sensitive value suppressed*"
2023-10-10 10:07:17         sensitive false
2023-10-10 10:07:17         domain nil
2023-10-10 10:07:17         user nil
2023-10-10 10:07:17         not_if { #code block }
2023-10-10 10:07:17       end
2023-10-10 10:07:17       
2023-10-10 10:07:17       System Info:
2023-10-10 10:07:17       ------------
2023-10-10 10:07:17       chef_version=17.10.0
2023-10-10 10:07:17       platform=ubuntu
2023-10-10 10:07:17       platform_version=22.04
2023-10-10 10:07:17       ruby=ruby 3.0.6p216 (2023-03-30 revision 23a532679b) [aarch64-linux]
2023-10-10 10:07:17       program_name=/opt/gitlab/embedded/bin/cinc-client
2023-10-10 10:07:17       executable=/opt/gitlab/embedded/bin/cinc-client
2023-10-10 10:07:17       
2023-10-10 10:07:17     
2023-10-10 10:07:17     ================================================================================
2023-10-10 10:07:17     Error executing action `run` on resource 'rails_migration[gitlab-rails]'
2023-10-10 10:07:17     ================================================================================
2023-10-10 10:07:17     
2023-10-10 10:07:17     Mixlib::ShellOut::ShellCommandFailed
2023-10-10 10:07:17     ------------------------------------
2023-10-10 10:07:17     bash_hide_env[migrate gitlab-rails database] (gitlab::database_migrations line 20) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
2023-10-10 10:07:17     ---- Begin output of "bash"  ----
2023-10-10 10:07:17     STDOUT: rake aborted!
2023-10-10 10:07:17     ActiveRecord::DatabaseConnectionError: There is an issue connecting to your database with your username/password, username: gitlab.
2023-10-10 10:07:17     
2023-10-10 10:07:17     Please check your database configuration to ensure the username/password are valid.
2023-10-10 10:07:17     /opt/gitlab/embedded/service/gitlab-rails/lib/gitlab/database/load_balancing/load_balancer.rb:116:in `read_write'
2023-10-10 10:07:17     /opt/gitlab/embedded/service/gitlab-rails/lib/gitlab/database/load_balancing/connection_proxy.rb:126:in `write_using_load_balancer'
2023-10-10 10:07:17     /opt/gitlab/embedded/service/gitlab-rails/lib/gitlab/database/load_balancing/connection_proxy.rb:96:in `method_missing'
2023-10-10 10:07:17     /opt/gitlab/embedded/service/gitlab-rails/lib/tasks/gitlab/db.rake:115:in `configure_database'
2023-10-10 10:07:17     /opt/gitlab/embedded/service/gitlab-rails/lib/tasks/gitlab/db.rake:101:in `block (3 levels) in <top (required)>'
2023-10-10 10:07:17     /opt/gitlab/embedded/bin/bundle:25:in `load'
2023-10-10 10:07:17     /opt/gitlab/embedded/bin/bundle:25:in `<main>'
2023-10-10 10:07:17     
2023-10-10 10:07:17     Caused by:
2023-10-10 10:07:17     PG::ConnectionBad: connection to server on socket "/var/opt/gitlab/postgresql/.s.PGSQL.5432" failed: No such file or directory
2023-10-10 10:07:17     Is the server running locally and accepting connections on that socket?
2023-10-10 10:07:17     /opt/gitlab/embedded/service/gitlab-rails/lib/gitlab/database/load_balancing/load_balancer.rb:116:in `read_write'
2023-10-10 10:07:17     /opt/gitlab/embedded/service/gitlab-rails/lib/gitlab/database/load_balancing/connection_proxy.rb:126:in `write_using_load_balancer'
2023-10-10 10:07:17     /opt/gitlab/embedded/service/gitlab-rails/lib/gitlab/database/load_balancing/connection_proxy.rb:96:in `method_missing'
2023-10-10 10:07:17     /opt/gitlab/embedded/service/gitlab-rails/lib/tasks/gitlab/db.rake:115:in `configure_database'
2023-10-10 10:07:17     /opt/gitlab/embedded/service/gitlab-rails/lib/tasks/gitlab/db.rake:101:in `block (3 levels) in <top (required)>'
2023-10-10 10:07:17     /opt/gitlab/embedded/bin/bundle:25:in `load'
2023-10-10 10:07:17     /opt/gitlab/embedded/bin/bundle:25:in `<main>'
2023-10-10 10:07:17     Tasks: TOP => gitlab:db:configure
2023-10-10 10:07:17     (See full trace by running task with --trace)
2023-10-10 10:07:17     STDERR: 
2023-10-10 10:07:17     ---- End output of "bash"  ----
2023-10-10 10:07:17     Ran "bash"  returned 1
2023-10-10 10:07:17     
2023-10-10 10:07:17     Cookbook Trace: (most recent call first)
2023-10-10 10:07:17     ----------------------------------------
2023-10-10 10:07:17     /opt/gitlab/embedded/cookbooks/cache/cookbooks/gitlab/resources/rails_migration.rb:20:in `block in class_from_file'
2023-10-10 10:07:17     
2023-10-10 10:07:17     Resource Declaration:
2023-10-10 10:07:17     ---------------------
2023-10-10 10:07:17     # In /opt/gitlab/embedded/cookbooks/cache/cookbooks/gitlab/recipes/database_migrations.rb
2023-10-10 10:07:17     
2023-10-10 10:07:17      51: rails_migration "gitlab-rails" do
2023-10-10 10:07:17      52:   rake_task 'gitlab:db:configure'
2023-10-10 10:07:17      53:   logfile_prefix 'gitlab-rails-db-migrate'
2023-10-10 10:07:17      54:   helper migration_helper
2023-10-10 10:07:17      55: 
2023-10-10 10:07:17      56:   environment env_variables
2023-10-10 10:07:17      57:   dependent_services dependent_services
2023-10-10 10:07:17      58:   notifies :run, "execute[clear the gitlab-rails cache]", :immediately
2023-10-10 10:07:17      59:   notifies :run, "ruby_block[check remote PG version]", :immediately
2023-10-10 10:07:17      60: 
2023-10-10 10:07:17      61:   only_if { migration_helper.attributes_node['auto_migrate'] }
2023-10-10 10:07:17      62: end
2023-10-10 10:07:17     
2023-10-10 10:07:17     Compiled Resource:
2023-10-10 10:07:17     ------------------
2023-10-10 10:07:17     # Declared in /opt/gitlab/embedded/cookbooks/cache/cookbooks/gitlab/recipes/database_migrations.rb:51:in `from_file'
2023-10-10 10:07:17     
2023-10-10 10:07:17     rails_migration("gitlab-rails") do
2023-10-10 10:07:17       action [:run]
2023-10-10 10:07:17       default_guard_interpreter :default
2023-10-10 10:07:17       declared_type :rails_migration
2023-10-10 10:07:17       cookbook_name "gitlab"
2023-10-10 10:07:17       recipe_name "database_migrations"
2023-10-10 10:07:17       rake_task "gitlab:db:configure"
2023-10-10 10:07:17       logfile_prefix "gitlab-rails-db-migrate"
2023-10-10 10:07:17       helper "*sensitive value suppressed*"
2023-10-10 10:07:17       environment "*sensitive value suppressed*"
2023-10-10 10:07:17       dependent_services []
2023-10-10 10:07:17       only_if { #code block }
2023-10-10 10:07:17     end
2023-10-10 10:07:17     
2023-10-10 10:07:17     System Info:
2023-10-10 10:07:17     ------------
2023-10-10 10:07:17     chef_version=17.10.0
2023-10-10 10:07:17     platform=ubuntu
2023-10-10 10:07:17     platform_version=22.04
2023-10-10 10:07:17     ruby=ruby 3.0.6p216 (2023-03-30 revision 23a532679b) [aarch64-linux]
2023-10-10 10:07:17     program_name=/opt/gitlab/embedded/bin/cinc-client
2023-10-10 10:07:17     executable=/opt/gitlab/embedded/bin/cinc-client
2023-10-10 10:07:17     
2023-10-10 10:07:17 [2023-10-10T08:07:17+00:00] INFO: Running queued delayed notifications before re-raising exception
2023-10-10 10:07:17 [2023-10-10T08:07:17+00:00] INFO: templatesymlink[Create a gitlab.yml and create a symlink to Rails root] sending run action to execute[clear the gitlab-rails cache] (delayed)
2023-10-10 10:07:17 Recipe: gitlab::gitlab-rails
2023-10-10 10:07:27   * execute[clear the gitlab-rails cache] action run[2023-10-10T08:07:27+00:00] INFO: execute[clear the gitlab-rails cache] ran successfully
2023-10-10 10:07:27 
2023-10-10 10:07:27     - execute /opt/gitlab/bin/gitlab-rake cache:clear
2023-10-10 10:07:27 [2023-10-10T08:07:27+00:00] INFO: version_file[Create version file for Gitaly] sending hup action to runit_service[gitaly] (delayed)
2023-10-10 10:07:27 Recipe: gitaly::enable
2023-10-10 10:07:27   * runit_service[gitaly] action hup[2023-10-10T08:07:27+00:00] INFO: runit_service[gitaly] signalled (HUP)
2023-10-10 10:07:27 [2023-10-10T08:07:27+00:00] INFO: runit_service[gitaly] sent hup
2023-10-10 10:07:27 
2023-10-10 10:07:27     - send hup to runit_service[gitaly]
2023-10-10 10:07:27 [2023-10-10T08:07:27+00:00] INFO: version_file[Create version file for Gitlab KAS] sending restart action to runit_service[gitlab-kas] (delayed)
2023-10-10 10:07:27 Recipe: gitlab-kas::enable
2023-10-10 10:07:37   * runit_service[gitlab-kas] action restart (up to date)
2023-10-10 10:07:37 
2023-10-10 10:07:37 Running handlers:
2023-10-10 10:07:37 [2023-10-10T08:07:37+00:00] ERROR: Running exception handlers
2023-10-10 10:07:37 There was an error running gitlab-ctl reconfigure:
2023-10-10 10:07:37 
2023-10-10 10:07:37 rails_migration[gitlab-rails] (gitlab::database_migrations line 51) had an error: Mixlib::ShellOut::ShellCommandFailed: bash_hide_env[migrate gitlab-rails database] (gitlab::database_migrations line 20) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
2023-10-10 10:07:37 ---- Begin output of "bash"  ----
2023-10-10 10:07:37 STDOUT: rake aborted!
2023-10-10 10:07:37 ActiveRecord::DatabaseConnectionError: There is an issue connecting to your database with your username/password, username: gitlab.
2023-10-10 10:07:37 
2023-10-10 10:07:37 Please check your database configuration to ensure the username/password are valid.
2023-10-10 10:07:37 /opt/gitlab/embedded/service/gitlab-rails/lib/gitlab/database/load_balancing/load_balancer.rb:116:in `read_write'
2023-10-10 10:07:37 /opt/gitlab/embedded/service/gitlab-rails/lib/gitlab/database/load_balancing/connection_proxy.rb:126:in `write_using_load_balancer'
2023-10-10 10:07:37 /opt/gitlab/embedded/service/gitlab-rails/lib/gitlab/database/load_balancing/connection_proxy.rb:96:in `method_missing'
2023-10-10 10:07:37 /opt/gitlab/embedded/service/gitlab-rails/lib/tasks/gitlab/db.rake:115:in `configure_database'
2023-10-10 10:07:37 /opt/gitlab/embedded/service/gitlab-rails/lib/tasks/gitlab/db.rake:101:in `block (3 levels) in <top (required)>'
2023-10-10 10:07:37 /opt/gitlab/embedded/bin/bundle:25:in `load'
2023-10-10 10:07:37 /opt/gitlab/embedded/bin/bundle:25:in `<main>'
2023-10-10 10:07:37 
2023-10-10 10:07:37 Caused by:
2023-10-10 10:07:37 PG::ConnectionBad: connection to server on socket "/var/opt/gitlab/postgresql/.s.PGSQL.5432" failed: No such file or directory
2023-10-10 10:07:37 Is the server running locally and accepting connections on that socket?
2023-10-10 10:07:37 /opt/gitlab/embedded/service/gitlab-rails/lib/gitlab/database/load_balancing/load_balancer.rb:116:in `read_write'
2023-10-10 10:07:37 /opt/gitlab/embedded/service/gitlab-rails/lib/gitlab/database/load_balancing/connection_proxy.rb:126:in `write_using_load_balancer'
2023-10-10 10:07:37 /opt/gitlab/embedded/service/gitlab-rails/lib/gitlab/database/load_balancing/connection_proxy.rb:96:in `method_missing'
2023-10-10 10:07:37 /opt/gitlab/embedded/service/gitlab-rails/lib/tasks/gitlab/db.rake:115:in `configure_database'
2023-10-10 10:07:37 /opt/gitlab/embedded/service/gitlab-rails/lib/tasks/gitlab/db.rake:101:in `block (3 levels) in <top (required)>'
2023-10-10 10:07:37 /opt/gitlab/embedded/bin/bundle:25:in `load'
2023-10-10 10:07:37 /opt/gitlab/embedded/bin/bundle:25:in `<main>'
2023-10-10 10:07:37 Tasks: TOP => gitlab:db:configure
2023-10-10 10:07:37 (See full trace by running task with --trace)
2023-10-10 10:07:37 STDERR: 
2023-10-10 10:07:37 ---- End output of "bash"  ----
2023-10-10 10:07:37 Ran "bash"  returned 1
2023-10-10 10:07:37 
2023-10-10 10:07:37 
2023-10-10 10:07:37 Notes:
2023-10-10 10:07:37 Default admin account has been configured with following details:
2023-10-10 10:07:37 Username: root
2023-10-10 10:07:37 Password: You didn't opt-in to print initial root password to STDOUT.
2023-10-10 10:07:37 Password stored to /etc/gitlab/initial_root_password. This file will be cleaned up in first reconfigure run after 24 hours.
2023-10-10 10:07:37 
2023-10-10 10:07:37 NOTE: Because these credentials might be present in your log files in plain text, it is highly recommended to reset the password following https://docs.gitlab.com/ee/security/reset_user_password.html#reset-your-root-password.
2023-10-10 10:07:37 
2023-10-10 10:07:37 Running handlers complete
2023-10-10 10:07:37 [2023-10-10T08:07:37+00:00] ERROR: Exception handlers complete
2023-10-10 10:07:37 Infra Phase failed. 272 resources updated in 01 minutes 33 seconds
2023-10-10 10:07:37 
2023-10-10 10:07:37 Notes:
2023-10-10 10:07:37 Default admin account has been configured with following details:
2023-10-10 10:07:37 Username: root
2023-10-10 10:07:37 Password: You didn't opt-in to print initial root password to STDOUT.
2023-10-10 10:07:37 Password stored to /etc/gitlab/initial_root_password. This file will be cleaned up in first reconfigure run after 24 hours.
2023-10-10 10:07:37 
2023-10-10 10:07:37 NOTE: Because these credentials might be present in your log files in plain text, it is highly recommended to reset the password following https://docs.gitlab.com/ee/security/reset_user_password.html#reset-your-root-password.
2023-10-10 10:07:37 
2023-10-10 10:07:37 [2023-10-10T08:07:37+00:00] FATAL: Stacktrace dumped to /opt/gitlab/embedded/cookbooks/cache/cinc-stacktrace.out
2023-10-10 10:07:37 [2023-10-10T08:07:37+00:00] FATAL: ---------------------------------------------------------------------------------------
2023-10-10 10:07:37 [2023-10-10T08:07:37+00:00] FATAL: PLEASE PROVIDE THE CONTENTS OF THE stacktrace.out FILE (above) IF YOU FILE A BUG REPORT
2023-10-10 10:07:37 [2023-10-10T08:07:37+00:00] FATAL: ---------------------------------------------------------------------------------------
2023-10-10 10:07:37 [2023-10-10T08:07:37+00:00] FATAL: Mixlib::ShellOut::ShellCommandFailed: rails_migration[gitlab-rails] (gitlab::database_migrations line 51) had an error: Mixlib::ShellOut::ShellCommandFailed: bash_hide_env[migrate gitlab-rails database] (gitlab::database_migrations line 20) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
2023-10-10 10:07:37 ---- Begin output of "bash"  ----
2023-10-10 10:07:37 STDOUT: rake aborted!
```

**Comment by gsdukbh** [comment]
This image is the same as the official GitLab usage, you can see it here [Gitlab docker](https://docs.gitlab.com/ee/install/docker.html)

**Comment by dvorst** [comment]
I suspected that to be the case, unfortunately those instructions cause it to fail for me, guess I'll have to dig deeper. Thanks for the quick response!

**Comment by gsdukbh** [comment]
Actually I haven't tested the latest version, I'm using `v16.1.0-ee`, maybe it's a version issue, there's also a problem that it needs at least 4GB of RAM to work properly . 

Here is my deployment using `docker compose `, 
```yaml
version: '3.7'
services:
  gitlab:
    image: gsdukbh/gitlab-ee-arm64:latest
    container_name: gitlab
    volumes:
      - './gitlab/config:/etc/gitlab'
      - './gitlab/log:/var/log/gitlab'
      - './gitlab/data:/var/opt/gitlab'
    restart: always
    ports:
      - '9000:80'
      - '8090:8091' 
      - '2222:22'
  git-runner:
    image: gitlab/gitlab-runner:latest
    container_name: runner
    volumes: 
      - '/var/run/docker.sock:/var/run/docker.sock'
      - './runner/config:/etc/gitlab-runner'
    restart: always
    links:
     - 'gitlab:gitlab'

```

**Comment by dvorst** [comment]
Thanks for the response! 
I resolved the issue by creating docker volumes instead of binding mounts to my local disk. Everything works smoothly now, thanks for the help!

```
docker run \
  --detach \
  --hostname gitlab.example.com \
  --publish 443:443 --publish 80:80 --publish 22:22 \
  --name gitlab \
  --restart always \
  --volume gitlab-config:/etc/gitlab \
  --volume gitlab-logs:/var/log/gitlab \
  --volume gitlab-data:/var/opt/gitlab \
  --shm-size 256m \
  gsdukbh/gitlab-ee-arm64
```
